-- Aura X: Supabase data layer
create table if not exists public.aurax_documents (
  collection text not null,
  doc_id text not null,
  data jsonb not null default '{}'::jsonb,
  owner_uid uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (collection, doc_id)
);
create index if not exists aurax_documents_collection_idx on public.aurax_documents(collection);
create index if not exists aurax_documents_updated_idx on public.aurax_documents(updated_at desc);
alter table public.aurax_documents disable row level security;


create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  username text not null,
  endpoint text not null unique,
  subscription jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists push_subscriptions_username_idx on public.push_subscriptions(username);
alter table public.push_subscriptions disable row level security;

create or replace function public.aurax_delete_my_account()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  current_email text;
begin
  select email into current_email from auth.users where id = auth.uid();
  delete from public.push_subscriptions where username in (
    select doc_id from public.aurax_documents where collection='users' and lower(coalesce(data->>'googleEmail', data->>'email','')) = lower(coalesce(current_email,''))
  );
  delete from public.aurax_documents
  where (collection='users' and lower(coalesce(data->>'googleEmail', data->>'email','')) = lower(coalesce(current_email,'')))
     or (data->>'author' is not null and data->>'author' = coalesce((select doc_id from public.aurax_documents where collection='users' and lower(coalesce(data->>'googleEmail', data->>'email','')) = lower(coalesce(current_email,'')) limit 1),''));
  delete from auth.users where id = auth.uid();
end;
$$;
grant execute on function public.aurax_delete_my_account() to authenticated;

-- Web Push / Edge Function setup helpers
-- 1) supabase functions deploy send-push
-- 2) set secrets VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT
-- 3) copy the public key into index.html -> VAPID_PUBLIC_KEY
